"""Matching-walk invariance gate: template assignment must be bit-identical to the
pre-change matcher (golden generated by tests/gen_golden.py on origin/development)."""
import json
from detectmateperformance.match_tree import TreeMatcher


def test_template_assignment_matches_golden():
    with open("tests/test_data/audit.log") as f:
        logs = ["):".join(line.split("):")[1:]) for line in f.readlines()]
    with open("tests/test_data/audit_golden_event_ids.json") as f:
        golden = json.load(f)
    res = TreeMatcher.from_file("tests/test_data/audit_templates.txt").match_batch(logs, True, n_workers=1)
    assert res.get_all_events_ids() == golden
