services:
  arm64_builder:
    image: arm64v8/gcc:latest
    container_name: arm64_builder
    platform: linux/arm64
    command: ["sh", "install_compile.sh"]

  x86_64_builder:
    image: gcc:latest
    container_name: x86_64_builder
    volumes:
      - ./:/app
    working_dir: /app
    command: ["sh", "install_compile.sh"]
