name: Python application

on:
  push:
    branches: [ "main", "development"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v6.6.0
        with:
          python-version: "3.12"
          activate-environment: true
          enable-cache: true

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Vienna

      - name: Run pre-commit with prek
        run: uv run --dev prek run -a

      - name: Test with pytest
        run: uv run --dev pytest -s
